name: build-core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        npm ci
        
        for file in configs/examples/*.example.json; do
          filename=$(basename "$file" .example.json)
          new_filename="${filename%.example}"
          
          cp "$file" "configs/$new_filename.json"
        done

        cp configs/examples/config.example.json config.json

        npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Run eslint
      run: |
        npm ci

        for file in configs/examples/*.example.json; do
          filename=$(basename "$file" .example.json)
          new_filename="${filename%.example}"
          
          cp "$file" "configs/$new_filename.json"
        done

        cp configs/examples/config.example.json config.json

        npm run lint
